public void upload() {
  //// select item with id and token combination
  //entityDS.id(UserID).token(UserID);
  
  //entityDS
  //  //User's Household Characteristics
  //  .data("001_Characteristics_Done", CharacteristicsDone)
  //  .data("002_Household_Type", HouseholdType)
  //  .data("003_House_Type", HouseType)
  //  .data("004_User_Gender", o1Gender)
  //  .data("005_User_Age", o1Age)
  //  .data("006_User_Edu", o1Edu)
  //  .data("007_User_Tech", o1Tech)
  //  .data("008_User_Home", o1Home)
  //  .data("008_oc2_Gender", o2Gender)
  //  .data("009_oc2_Age", o2Age)
  //  .data("010_oc2_Edu", o2Edu)
  //  .data("011_oc2_Tech", o2Tech)
  //  .data("012_oc2_Home", o2Home)
  //  .data("013_oc3_Gender", o3Gender)
  //  .data("014_oc3_Age", o3Age)
  //  .data("015_oc3_Edu", o3Edu)
  //  .data("016_oc3_Tech", o3Tech)
  //  .data("017_oc3_Home", o3Home)
  //  .data("018_oc4_Gender", o4Gender)
  //  .data("019_oc4_Age", o4Age)
  //  .data("020_oc4_Edu", o4Edu)
  //  .data("021_oc4_Tech", o4Tech)
  //  .data("022_oc4_Home", o4Home)
  //  .data("023_oc5_Gender", o5Gender)
  //  .data("024_oc5_Age", o5Age)
  //  .data("025_oc5_Edu", o5Edu)
  //  .data("026_oc5_Tech", o5Tech)
  //  .data("027_oc5_Home", o5Home)
  //  .data("028_oc6_Gender", o6Gender)
  //  .data("029_oc6_Age", o6Age)
  //  .data("030_oc6_Edu", o6Edu)
  //  .data("031_oc6_Tech", o6Tech)
  //  .data("032_oc6_Home", o6Home)
    
  //  //Predicted Intentions
  //  .data("033_Profile_Selected", profileSelected)
  //  .data("034_A_Sustainability", predictionResult_Sustainability)
  //  .data("035_A_Security", predictionResult_Security)
  //  .data("036_A_Convenience", predictionResult_Convenience)
  //  .data("037_A_Privacy", predictionResult_Privacy)
  //  .data("038_A_Personalization", predictionResult_Personalization)
  //  .data("039_A_Control", predictionResult_Control)
  //  .data("040_B_Sustainability", alternateB_Sustainability)
  //  .data("041_B_Security", alternateB_Security)
  //  .data("042_B_Convenience", alternateB_Convenience)
  //  .data("043_B_Privacy", alternateB_Privacy)
  //  .data("044_B_Personalization", alternateB_Personalization)
  //  .data("045_B_Control", alternateB_Control)
  //  .data("046_C_Sustainability", alternateC_Sustainability)
  //  .data("047_C_Security", alternateC_Security)
  //  .data("048_C_Convenience", alternateC_Convenience)
  //  .data("049_C_Privacy", alternateC_Privacy)
  //  .data("050_C_Personalization", alternateC_Personalization)
  //  .data("051_C_Control", alternateC_Control)
    
  //  //Final Intentions
  //  .data("052_Final_Sustainability", sustainabilityValue)
  //  .data("053_Final_Security", securityValue)
  //  .data("054_Final_Convenience", convenienceValue)
  //  .data("055_Final_Privacy", privacyValue)
  //  .data("056_Final_Personalization", personalizationValue)
  //  .data("057_Final_Control", controlValue)
    
  //  //Predicted Preferences
  //  .data("058_Prediction_LightingSunlight", predictionResult_LightingSunlight)
  //  .data("059_Prediction_LightingMovement", predictionResult_LightingMovement)
  //  .data("060_Prediction_LightingVacated", predictionResult_LightingVacated)
  //  .data("061_Prediction_LightingBedtime", predictionResult_LightingBedtime)
  //  .data("062_Prediction_LightingNever", predictionResult_LightingNever)
  //  .data("063_Prediction_ClimateHome", predictionResult_ClimateHome)
  //  .data("064_Prediction_ClimateAwake", predictionResult_ClimateAwake)
  //  .data("065_Prediction_ClimateNever", predictionResult_ClimateNever)
  //  .data("066_Prediction_SecurityAlways", predictionResult_SecurityAlways)
  //  .data("067_Prediction_SecurityMovement", predictionResult_SecurityMovement)
  //  .data("068_Prediction_SecurityVacated", predictionResult_SecurityVacated)
  //  .data("069_Prediction_SecuritySleeping", predictionResult_SecuritySleeping)
  //  .data("070_Prediction_SecurityNever", predictionResult_SecurityNever)
  //  .data("071_Prediction_NotificationsMovement", predictionResult_NotificationsMovement)
  //  .data("072_Prediction_NotificationsAlarm", predictionResult_NotificationsAlarm)
  //  .data("073_Prediction_NotificationsDoorbell", predictionResult_NotificationsDoorbell)
  //  .data("074_Prediction_NotificationsTraffic", predictionResult_NotificationsTraffic)
  //  .data("075_Prediction_NotificationsEnergy", predictionResult_NotificationsEnergy)
  //  .data("076_Prediction_NotificationsNever", predictionResult_NotificationsNever)
  //  .data("077_Prediction_ProgrammingMyself", predictionResult_ProgrammingMyself)
  //  .data("079Prediction_ProgrammingPartner", predictionResult_ProgrammingPartner)
  //  .data("080_Prediction_ProgrammingOccupant", predictionResult_ProgrammingOccupant)
  //  .data("081Prediction_ProgrammingCompany", predictionResult_ProgrammingCompany)
    
  //  //Final Preferences
  //  .data("082_Final_LightingSunlight", cp5.get(CheckBox.class, "lighting").getState(0))
  //  .data("083_Final_LightingVacated", cp5.get(CheckBox.class, "lighting").getState(1))
  //  .data("084_Final_LightingMovement", cp5.get(CheckBox.class, "lighting").getState(2))
  //  .data("085_Final_LightingNever", cp5.get(CheckBox.class, "lighting").getState(3))
  //  .data("086_Final_LightingBedtime", cp5.get(CheckBox.class, "lighting").getState(4))
  //  .data("087_Final_ClimateHome", cp5.get(CheckBox.class, "climate").getState(0))
  //  .data("088_Final_ClimateAlways", cp5.get(CheckBox.class, "climate").getState(1))
  //  .data("089_Final_ClimateAwake", cp5.get(CheckBox.class, "climate").getState(2))
  //  .data("090_Final_ClimateNever", cp5.get(CheckBox.class, "climate").getState(3))
  //  .data("091_Final_SecurityMovement", cp5.get(CheckBox.class, "securitysettings").getState(0))    
  //  .data("092_Final_SecurityAlways", cp5.get(CheckBox.class, "securitysettings").getState(1))
  //  .data("093_Final_SecurityVacated", cp5.get(CheckBox.class, "securitysettings").getState(2))
  //  .data("094_Final_SecurityNever", cp5.get(CheckBox.class, "securitysettings").getState(3))    
  //  .data("095_Final_SecuritySleeping", cp5.get(CheckBox.class, "securitysettings").getState(4))
  //  .data("096_Final_NotificationsDoorbell", cp5.get(CheckBox.class, "notifications").getState(0))
  //  .data("097_Final_NotificationsTraffic", cp5.get(CheckBox.class, "notifications").getState(1))
  //  .data("098_Final_NotificationsAlarm", cp5.get(CheckBox.class, "notifications").getState(2))    
  //  .data("099_Final_NotificationsEnergy", cp5.get(CheckBox.class, "notifications").getState(3))
  //  .data("100_Final_NotificationsMovement", cp5.get(CheckBox.class, "notifications").getState(4))    
  //  .data("101_Final_NotificationsNever", cp5.get(CheckBox.class, "notifications").getState(5))
  //  .data("102_Final_ProgrammingMyself", cp5.get(CheckBox.class, "programming").getState(0))
  //  .data("103_Final_ProgrammingPartner", cp5.get(CheckBox.class, "programming").getState(1))
  //  .data("104_Final_ProgrammingOccupant", cp5.get(CheckBox.class, "programming").getState(2))
  //  .data("105_Final_ProgrammingCompany", cp5.get(CheckBox.class, "programming").getState(3))
    
  //  .update()
    ;

}
  
